// ================= API routes =================
//
// One place that names every endpoint. The server matches on these patterns
// and the client builds URLs from the same helpers.

const enc = encodeURIComponent;

export const routes = {
  state: () => "/api/state",
  glance: () => "/api/glance",
  glanceSeen: () => "/api/glance/seen",
  glanceCurate: () => "/api/glance/curate",
  projectBrief: (pid: string) => `/api/projects/${enc(pid)}/brief`,
  budgets: () => "/api/budgets",
  workspace: () => "/api/workspace",
  projects: () => "/api/projects",
  project: (pid: string) => `/api/projects/${enc(pid)}`,
  targets: (pid: string) => `/api/projects/${enc(pid)}/targets`,
  milestones: (pid: string) => `/api/projects/${enc(pid)}/milestones`,
  milestone: (pid: string, mid: string) => `/api/projects/${enc(pid)}/milestones/${enc(mid)}`,
  readings: (pid: string, mid: string, xid: string) => `/api/projects/${enc(pid)}/milestones/${enc(mid)}/metrics/${enc(xid)}/readings`,
  governanceItems: (pid: string) => `/api/projects/${enc(pid)}/governance`,
  governance: (pid: string, gid: string) => `/api/projects/${enc(pid)}/governance/${enc(gid)}`,
  releases: (pid: string) => `/api/projects/${enc(pid)}/releases`,
  release: (pid: string, rid: string) => `/api/projects/${enc(pid)}/releases/${enc(rid)}`,
  sync: (pid: string) => `/api/projects/${enc(pid)}/sync`,
  syncStatus: () => "/api/sync",
  agents: () => "/api/agents",
  agentRuns: (aid: string) => `/api/agents/${enc(aid)}/runs`,
  templates: () => "/api/templates",
  templateCreate: (tid: string) => `/api/templates/${enc(tid)}/create`,
  templateVersions: (tid: string) => `/api/templates/${enc(tid)}/versions`,
  projectUpdate: (pid: string) => `/api/projects/${enc(pid)}/update`,
  projectDrift: (pid: string) => `/api/projects/${enc(pid)}/drift`,
  workspaceExport: () => "/api/workspace/export",
  workspaceImport: () => "/api/workspace/import",
  setup: () => "/api/setup",
  setupDraft: (id: string) => `/api/setup/${enc(id)}`,
  setupRefine: (id: string) => `/api/setup/${enc(id)}/refine`,
  setupCreate: (id: string) => `/api/setup/${enc(id)}/create`,
  chat: () => "/api/chat",
  run: (id: string) => `/api/runs/${enc(id)}`,
  runRate: (id: string) => `/api/runs/${enc(id)}/rate`,
  runEvents: (id: string) => `/api/runs/${enc(id)}/events`,
  live: () => "/api/live",
  runJudge: (id: string) => `/api/runs/${enc(id)}/judge`,
  benchmark: () => "/api/evals/benchmark",
  scout: () => "/api/evals/scout",
  agentPrompt: (aid: string) => `/api/agents/${enc(aid)}/prompt`,
  rules: () => "/api/rules",
  rule: (id: string) => `/api/rules/${enc(id)}`,
  proposalAccept: (id: string) => `/api/proposals/${enc(id)}/accept`,
  proposalDismiss: (id: string) => `/api/proposals/${enc(id)}/dismiss`,
  calendar: () => "/api/calendar",
  calendarEvent: (id: string) => `/api/calendar/${enc(id)}`,
  commsAssignments: () => "/api/comms/assignments",
  commsAssignment: (id: string) => `/api/comms/assignments/${enc(id)}`,
  commsRun: (id: string) => `/api/comms/assignments/${enc(id)}/run`,
  commsArtifacts: (projectId?: string) => `/api/comms/artifacts${projectId ? `?projectId=${enc(projectId)}` : ""}`,
  commsArtifact: (id: string) => `/api/comms/artifacts/${enc(id)}`,
  commsDownload: (id: string, format: "md" | "txt" = "md") => `/api/comms/artifacts/${enc(id)}/download?format=${format}`,
  pmAssignments: () => "/api/pm/assignments",
  pmAssignment: (id: string) => `/api/pm/assignments/${enc(id)}`,
  pmRun: (id: string) => `/api/pm/assignments/${enc(id)}/run`,
  pmRuns: (id: string) => `/api/pm/assignments/${enc(id)}/runs`,
} as const;

/** Route patterns (Bun.serve-style `:param` segments) in match order. */
export const patterns = {
  state: "/api/state",
  glance: "/api/glance",
  glanceSeen: "/api/glance/seen",
  glanceCurate: "/api/glance/curate",
  projectBrief: "/api/projects/:pid/brief",
  budgets: "/api/budgets",
  workspace: "/api/workspace",
  projects: "/api/projects",
  project: "/api/projects/:pid",
  targets: "/api/projects/:pid/targets",
  milestones: "/api/projects/:pid/milestones",
  milestone: "/api/projects/:pid/milestones/:mid",
  readings: "/api/projects/:pid/milestones/:mid/metrics/:xid/readings",
  governanceItems: "/api/projects/:pid/governance",
  governance: "/api/projects/:pid/governance/:gid",
  releases: "/api/projects/:pid/releases",
  release: "/api/projects/:pid/releases/:rid",
  sync: "/api/projects/:pid/sync",
  syncStatus: "/api/sync",
  agents: "/api/agents",
  agentRuns: "/api/agents/:aid/runs",
  templates: "/api/templates",
  templateCreate: "/api/templates/:tid/create",
  templateVersions: "/api/templates/:tid/versions",
  projectUpdate: "/api/projects/:pid/update",
  projectDrift: "/api/projects/:pid/drift",
  workspaceExport: "/api/workspace/export",
  workspaceImport: "/api/workspace/import",
  setup: "/api/setup",
  setupDraft: "/api/setup/:id",
  setupRefine: "/api/setup/:id/refine",
  setupCreate: "/api/setup/:id/create",
  chat: "/api/chat",
  run: "/api/runs/:id",
  runRate: "/api/runs/:id/rate",
  runEvents: "/api/runs/:id/events",
  live: "/api/live",
  runJudge: "/api/runs/:id/judge",
  benchmark: "/api/evals/benchmark",
  scout: "/api/evals/scout",
  agentPrompt: "/api/agents/:aid/prompt",
  rules: "/api/rules",
  rule: "/api/rules/:id",
  proposalAccept: "/api/proposals/:id/accept",
  proposalDismiss: "/api/proposals/:id/dismiss",
  calendar: "/api/calendar",
  calendarEvent: "/api/calendar/:id",
  commsAssignments: "/api/comms/assignments",
  commsAssignment: "/api/comms/assignments/:id",
  commsRun: "/api/comms/assignments/:id/run",
  commsArtifacts: "/api/comms/artifacts",
  commsArtifact: "/api/comms/artifacts/:id",
  commsDownload: "/api/comms/artifacts/:id/download",
  pmAssignments: "/api/pm/assignments",
  pmAssignment: "/api/pm/assignments/:id",
  pmRun: "/api/pm/assignments/:id/run",
  pmRuns: "/api/pm/assignments/:id/runs",
} as const;
